-- 风格库同步（2026-09-01 修正版：ON CONFLICT 匹配 016 部分唯一索引，幂等）
INSERT INTO style_keywords (style_name, keywords, description, enabled) VALUES ('实拍质感单品', '产品,实测,单品,开箱,评测,推荐', '真实产品实拍质感、自然光、浅景深特写、生活化场景、干净背景', False) ON CONFLICT (style_name) WHERE owner_id IS NULL DO UPDATE SET keywords=EXCLUDED.keywords, description=EXCLUDED.description, enabled=EXCLUDED.enabled, updated_at=now();
INSERT INTO style_keywords (style_name, keywords, description, enabled) VALUES ('双主体同框对比', '对比,评测,哪个好,区别,VS,和,还是,选', '两个主体左右同框对比构图、参数并排清晰、对比色块标注、公平呈现', False) ON CONFLICT (style_name) WHERE owner_id IS NULL DO UPDATE SET keywords=EXCLUDED.keywords, description=EXCLUDED.description, enabled=EXCLUDED.enabled, updated_at=now();
INSERT INTO style_keywords (style_name, keywords, description, enabled) VALUES ('米白扁平信息卡', '教育,升学,学校,择校,考研,专业,课程,政策,要点,清单,攻略,风险提醒,班型,师资,招生', '米白色背景低饱和扁平插画，墨绿/灰绿色系，黑色粗黑体大标题居上，圆形线性图标配圆角卡片清单，点缀植物枝叶与几何曲线装饰，大量留白，杂志式信息图排版，整体舒适自然', True) ON CONFLICT (style_name) WHERE owner_id IS NULL DO UPDATE SET keywords=EXCLUDED.keywords, description=EXCLUDED.description, enabled=EXCLUDED.enabled, updated_at=now();
INSERT INTO style_keywords (style_name, keywords, description, enabled) VALUES ('杂志风产品对比卡', '手机,数码,平板,手表,手环,耳机,家电,汽车,电动车,显卡,跑鞋,剃须刀,对比,测评,选购,怎么选', '浅奶油色或浅藕紫渐变纯色背景（可选摄影棚弧形墙面或石质台面），两台产品以高精度写实渲染左右对称，柔和影棚光与地面轻微倒影，中央大号VS字样，顶部超大粗黑标题加副标题加胶囊标签，中部栏目标签行（如 外观丨性能丨续航丨选购建议）做杂志目录式分栏，参数用细线刻度条标注，关键信息暖橘强调，底部一句话结论条，留白五成', True) ON CONFLICT (style_name) WHERE owner_id IS NULL DO UPDATE SET keywords=EXCLUDED.keywords, description=EXCLUDED.description, enabled=EXCLUDED.enabled, updated_at=now();
INSERT INTO style_keywords (style_name, keywords, description, enabled) VALUES ('中轴双栏对比卡', '对比,vs,哪个好,择校对比,学校对比,方案对比,价格对比,优劣', '画面沿中轴线左右对称分割为双色阵营（墨绿对藏蓝或绿对橙，均低饱和），双方各配写实场景图与图标要点列表，中央放VS或路标罗盘等对比符号，米白底黑体标题，信息图式排版', True) ON CONFLICT (style_name) WHERE owner_id IS NULL DO UPDATE SET keywords=EXCLUDED.keywords, description=EXCLUDED.description, enabled=EXCLUDED.enabled, updated_at=now();
INSERT INTO style_keywords (style_name, keywords, description, enabled) VALUES ('写实生活场景卡', '美食,菜谱,食材,做法,园艺,养花,生活妙招,科普,健康,养殖,种植,饮品,配方,甜品,炖汤,茶饮,冲饮', '奶油米或浅米黄低饱和暖底的写实摄影卡，棚拍柔光或自然光，浅景深虚化，实景照片用圆角矩形大图裁切占约半版，主体置于画面下半部或右侧，顶部大标题（粗黑体，美食配方类可用衬线宋体）配副标题，要点前配统一小圆图标，暖棕细分隔线与圆角卡片边框，静物教程可用奶油米配鼠尾草绿双色块曲线分割变体，关键信息暖橘强调，温暖治愈', True) ON CONFLICT (style_name) WHERE owner_id IS NULL DO UPDATE SET keywords=EXCLUDED.keywords, description=EXCLUDED.description, enabled=EXCLUDED.enabled, updated_at=now();
INSERT INTO style_keywords (style_name, keywords, description, enabled) VALUES ('航拍风光旅行卡', '旅游,自驾,路线,城市,宜居,景点,行程,风光,户外', '写实航拍城市/公路/田园风光大图占画面约三分之二，其余为奶白或浅米黄纸张感标题区，图与文字区以弧形曲线分割并配细金线或暖棕细线过渡，黑色/深棕粗体大标题加副标题，可少量点缀手账风贴纸/胶带/标签元素（不喧宾夺主），清爽旅行杂志感', True) ON CONFLICT (style_name) WHERE owner_id IS NULL DO UPDATE SET keywords=EXCLUDED.keywords, description=EXCLUDED.description, enabled=EXCLUDED.enabled, updated_at=now();
INSERT INTO style_keywords (style_name, keywords, description, enabled) VALUES ('水彩绘本插画卡', '规划,前景,路径,就业方向,人生选择,成长,目标,愿景', '柔和水彩质感的蜿蜒道路或阶梯通向远方，画面散布题材隐喻物（毕业帽/罗盘/天平等），蓝灰金或青绿淡雅色调，标题下配要点文字，梦幻留白构图', True) ON CONFLICT (style_name) WHERE owner_id IS NULL DO UPDATE SET keywords=EXCLUDED.keywords, description=EXCLUDED.description, enabled=EXCLUDED.enabled, updated_at=now();
INSERT INTO style_keywords (style_name, keywords, description, enabled) VALUES ('写实静物家居卡', '家居,收纳,洗护,母婴,厨房,百货,生活用品,好物', '米白/木质真实场景中的产品静物摄影，自然窗光影，画面上三分之一为纯色标题区（黑体主标题+副标题+彩色小标签），下三分之二为写实产品图，图与文字以弧线自然衔接，色调温暖治愈、低饱和', True) ON CONFLICT (style_name) WHERE owner_id IS NULL DO UPDATE SET keywords=EXCLUDED.keywords, description=EXCLUDED.description, enabled=EXCLUDED.enabled, updated_at=now();
INSERT INTO style_keywords (style_name, keywords, description, enabled) VALUES ('科技产品渲染卡', '芯片,处理器,AI,5G,科技,游戏,电竞,性能,算力', '浅灰米色或奶白纯色背景，科技产品以高精度写实3D渲染呈现、柔和影棚光、地面轻微倒影，参数以细线刻度条与数据卡片罗列，顶部超大粗黑标题，低饱和配色、大量留白，真实可信的棚拍质感', True) ON CONFLICT (style_name) WHERE owner_id IS NULL DO UPDATE SET keywords=EXCLUDED.keywords, description=EXCLUDED.description, enabled=EXCLUDED.enabled, updated_at=now();
INSERT INTO style_keywords (style_name, keywords, description, enabled) VALUES ('深色科技风', '性价比,千元机,跑分,参数,快充,电池,电竞,游戏手机,旗舰,测评', '炭黑或深灰近黑背景，琥珀橙高亮价格与重点数字，青蓝渐变霓虹光斑，产品以3D渲染小图呈现于圆角参数卡片内竖排堆叠（处理器/电池/快充/屏幕逐项列表），配芯片电池小图标，粗黑体大标题加无衬线数字，细线分割，硬核测评感、干净利落', True) ON CONFLICT (style_name) WHERE owner_id IS NULL DO UPDATE SET keywords=EXCLUDED.keywords, description=EXCLUDED.description, enabled=EXCLUDED.enabled, updated_at=now();
INSERT INTO style_keywords (style_name, keywords, description, enabled) VALUES ('手写暖心科普卡', '宠物,猫,狗,喝水,情绪,心理,治愈,冷知识,习惯,陪伴', '奶油米色背景，顶部写实摄影图（自然光），圆润手写体大标题，要点装在白色圆角标签内逐条排列，深绿强调色配深棕黑体正文，留白充足，温馨手作感而不花哨', True) ON CONFLICT (style_name) WHERE owner_id IS NULL DO UPDATE SET keywords=EXCLUDED.keywords, description=EXCLUDED.description, enabled=EXCLUDED.enabled, updated_at=now();
